In [9]:

import pandas as pd

In [15]:
df = pd.read_csv('sweet.csv', encoding='UTF-16', sep = '\t')

In [16]:
df

,Date,Time,Time Zone,Gross Sales,Discounts,Net Sales,Gift Card Sales,Tax,Tip,Partial Refunds,...,Device Nickname,Deposit ID,Deposit Date,Deposit Details,Fee Percentage Rate,Fee Fixed Rate,Refund Reason,E-money,Discount Name,Transaction Status
0,05/08/20,23:59:34,Mexico City,¥867,¥0,¥867,¥0,¥69,¥0,¥0,...,Nawate Cafe 1,NaN,NaN,NaN,NaN,NaN,NaN,¥0,NaN,Complete
1,05/08/20,23:56:56,Mexico City,¥851,¥0,¥851,¥0,¥68,¥0,¥0,...,Nawate Cafe 1,NaN,NaN,NaN,3.25,¥0,NaN,¥0,NaN,Complete
2,05/08/20,23:48:55,Mexico City,"¥1,331",¥0,"¥1,331",¥0,¥106,¥0,¥0,...,Nawate Cafe 1,NaN,NaN,NaN,NaN,NaN,NaN,¥0,NaN,Complete
3,05/08/20,23:36:51,Mexico City,¥835,¥0,¥835,¥0,¥66,¥0,¥0,...,Nawate Cafe 3,NaN,NaN,NaN,NaN,NaN,NaN,¥0,NaN,Complete
4,05/08/20,23:35:56,Mexico City,¥638,¥0,¥638,¥0,¥51,¥0,¥0,...,Nawate Cafe 1,NaN,NaN,NaN,3.25,¥0,NaN,¥0,NaN,Complete
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81,05/08/20,00:39:11,Mexico City,¥722,¥0,¥722,¥0,¥57,¥0,¥0,...,Nawate Cafe 1,NaN,NaN,NaN,NaN,NaN,NaN,¥0,NaN,Complete
82,05/08/20,00:31:52,Mexico City,¥741,¥0,¥741,¥0,¥59,¥0,¥0,...,Nawate Cafe 1,NaN,NaN,NaN,NaN,NaN,NaN,¥0,NaN,Complete
83,05/08/20,00:26:44,Mexico City,"¥1,396",¥0,"¥1,396",¥0,¥111,¥0,¥0,...,Nawate Cafe 1,NaN,NaN,NaN,3.25,¥0,NaN,¥0,NaN,Complete
84,05/08/20,00:19:59,Mexico City,"¥2,122",¥0,"¥2,122",¥0,¥169,¥0,¥0,...,Nawate Cafe 1,NaN,NaN,NaN,NaN,NaN,NaN,¥0,NaN,Complete
85,05/08/20,00:05:47,Mexico City,¥527,¥0,¥527,¥0,¥42,¥0,¥0,...,Nawate Cafe 1,NaN,NaN,NaN,NaN,NaN,NaN,¥0,NaN,Complete